import Todo from "@/components/Todo";
import Head from "next/head";
import { ChangeEvent, useState, FormEvent } from "react";

export default function Home() {
  const [todos, setTodos] = useState((): string[] => []);
  const [text, setText] = useState("");

  function InputChangeHandler(e: ChangeEvent<HTMLInputElement>) {
    setText(e.target.value);
  }

  function InputSubmitHandler(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    if (text) setTodos([...todos, text]);
    setText("");
  }

  function removeTodo(text: string) {
    setTodos(todos.filter((todo) => todo != text));
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container max-h-max">
        <div className="mt-10 p-6 max-w-md max-h-48 m-auto bg-white rounded-xl shadow-lg flex items-center space-x-4">
          <form className="w-full" onSubmit={InputSubmitHandler}>
            <input
              className="bg-white border-b-2 w-full"
              onChange={InputChangeHandler}
              value={text}
            ></input>
          </form>
        </div>
        <div className="max-w-sm mx-auto bg-inherit border-none"></div>
        <div className="mt-10 max-w-sm mx-auto">
          {todos.map((todo, i) => (
            <Todo text={todo} key={i} remove={removeTodo} />
          ))}
        </div>
      </div>
    </>
  );
}
